name: Build Check

on: 
  push: {}
  pull_request: {}
  workflow_dispatch:
jobs:
  check:
    strategy:
      matrix:
        go-version: [1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Check
      run: |
        make cloudflared
        pwd && ls
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudflared-${{ matrix.os }}
        path: ${{ matrix.os == 'windows-latest' && 'cloudflared.exe' || 'cloudflared' }}